### ISSUE TITLE
This is great :D

### ISSUE THREAD

**Issue by eboatwright** [kettle11/kudo#15]
Love this crate! I've been using HECS for a while, and it's just a bit bloated and overcomplicated in parts. This one is just like a simplified version of HECS, and I love it! Great work! Love the Greek Mythology references in the example :)

**Comment by kettle11** [comment]
Thanks! Always cool to have people actually using your code.

I should have documented this sooner, but I've continued to work on this crate as a sub-crate in my game engine: https://github.com/kettle11/koi/tree/main/crates/kecs

It's had a bunch of bug fixes and feature additions that I should probably note on this repository.

**Comment by eboatwright** [comment]
Ok thank you!
